### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by xhochy** [conda-forge/cross-python-feedstock#19]
It seems like we cannot cross-compile PyPy-based matrix entries currently. For example I come across with this in https://github.com/conda-forge/httptools-feedstock/pull/15 

Is this a limitation of PyPy / just missing support here / an artifact that we force the `python` in `build` to be the same as the one in host?

**Comment by chrisburr** [comment]
I've just ran into this as well while changing to cross-compile ppc64le.

@isuruf Do you know if there is anything fundamental blocking this? Or is it just a matter of modifying the `conda_build_config.yaml` in this repo?

**Comment by isuruf** [comment]
> crossenv doesn't seem to work out of the box with PyPy, so there probably is some work to be done.

What's the error that you are getting?

**Comment by mattip** [comment]
I hadn't seen it in the context of the conda-forge pypy3.7 before, thanks. I opened onda-forge/pypy3.6-feedstock#58 to make sure it gets fixed for the next build of pypy

**Comment by chrisburr** [comment]
> It seems the patches break venv creation on pypy3.7 since they change the layout to be like CPython

Aha! I wasn't expecting that and that makes a lot more sense 😄 Thanks for the quick response.

It would also be useful if `VERSION`  and `HOST_GNU_TYPE` could be included in the `build_time_vars` dictionary in `$PREFIX/lib_pypy/_sysconfigdata.py` as `crossenv` makes use of it.

**Comment by mattip** [comment]
The fix was added in conda-forge/pypy3.6-feedstock#71. Was it sufficient?

**Comment by isuruf** [comment]
Yes, we can cross compile scipy pypy wheels now.

**Comment by isuruf** [comment]
Upstream PR at https://foss.heptapod.net/pypy/pypy/-/merge_requests/841
