### ISSUE TITLE
Cross-python may fail to execute due to long shebang line.

### ISSUE THREAD

**Issue by kuepe-sl** [conda-forge/cross-python-feedstock#27]
While doing recent CI build of Python packages, I came across an annoying bug.

In our CI, the paths can get long due to the way the GitLab Runner stores repositories.
For one of the repos, I first got strange errors like

```
$PREFIX/bin/python: line 3: import: command not found
$PREFIX/bin/python: line 4: import: command not found
$PREFIX/bin/python: line 7: os.environ[PYTHON_CROSSENV]: command not found
$PREFIX/bin/python: line 10: syntax error near unexpected token `'_PYTHON_SYSCONFIGDATA_NAME','
$PREFIX/bin/python: line 10: `        '_PYTHON_SYSCONFIGDATA_NAME', 'PYTHONHOME', 'PYTHONPATH']:'
```

After some investigation, I found the root of the issue:
It is the first line in `$PREFIX/bin/python`:
```
#!$BUILD_PREFIX/venv/build/bin/python -I
```

or expanded:
```
#!/builds/xxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/builds/xxxxx_1625229677922/_build_env/venv/build/bin/python -I
```
The shebang line is 128 characters long - which is over the limit of 127 characters defined by the kernel. (as told in [this StackOverflow answer](https://stackoverflow.com/a/10813634)
Thus the build breaks.

Reproducing the issue on Ubuntu 18.04:
```
cd /tmp
mkdir dir-with-a-long-path-that-is-just--right
cd dir-with-a-long-path-that-is-just--right
git clone https://github.com/conda-forge/pyyaml-feedstock.git
conda build recipe/ -m .ci_support/linux_aarch64_python3.8.____cpythonpython_implcpython.yaml --keep-old-work --croot ./builds
```

It will then end up with
```
source tree in: /tmp/dir-with-a-long-path-that-is-just--right/pyyaml-feedstock/builds/pyyaml_1625243359814/work
export PREFIX=/tmp/dir-with-a-long-path-that-is-just--right/pyyaml-feedstock/builds/pyyaml_1625243359814/_h_env_placehold_placehold_placehold
export BUILD_PREFIX=/tmp/dir-with-a-long-path-that-is-just--right/pyyaml-feedstock/builds/pyyaml_1625243359814/_build_env
```
and should freeze.

Shebang from `$PREFIX/bin/python`:
```
#!/tmp/dir-with-a-long-path-that-is-just--right/pyyaml-feedstock/builds/pyyaml_1625243359814/_build_env/venv/build/bin/python -I
```
It freezes, because the shebang line is so long that it truncated it after the `-`.
It is effectively executing `python -` and thus waits for input in STDIN.

On Ubuntu 20.04 with a 5.8 kernel the limit appears to be higher - 255 characters instead of 127.
You can reproduce it there by naming the folder `dir-with-a-long-path-that-is-just-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-right`.

Environment:
- conda-4.10.3-py38h578d9bd_0
- conda-build-3.21.4-py38h578d9bd_0
- crossenv-1.0-pyhd8ed1ab_1
- cross-python_linux-aarch64-3.8-13_cpython

**Comment by isuruf** [comment]
This should be fixed with 1.1.2, but we haven't upgraded due to some issues I forget now.
Can you try building crossenv locally and see if that fixes that issue and cross compilation works fine?

**Comment by kuepe-sl** [comment]
I'll try that - thanks!

**Comment by kuepe-sl** [comment]
Unfortunately it still doesn't seem to work with 1.1.2:

```
    cross-python_linux-aarch64:   3.8-13_cpython            conda-forge                                 
    crossenv:                     1.1.2-pyhd8ed1ab_0        file:///home/user/local-conda-channel
    cython:                       0.29.23-py38h709712a_1    conda-forge                                 
    python:                       3.8.10-h49503c6_1_cpython conda-forge                                 
    python_abi:                   3.8-2_cp38                conda-forge                                 
[...]
```

**Comment by kuepe-sl** [comment]
An unpatched v1.1.0 does result in the same error with a *short* path.
... and v1.1.0 is not available in the conda-forge channel apparently?

**Comment by kuepe-sl** [comment]
The currently available version of crossenv appears to be 1.0 (despite v1.1.0 being in the repo).

Using this patch [long-path-fix.zip](https://github.com/conda-forge/cross-python-feedstock/files/6763037/long-path-fix.zip) (which is based on benfogle/crossenv#50), the cross-env build works properly.

What is the best way to continue here? Downgrade the crossenv repo back to v1.0 and applying the patch?
If that would be the way-to-go for now, I'd make a PR.

**Comment by isuruf** [comment]
Yes, that seems reasonable for now.

**Comment by kuepe-sl** [comment]
I can confirm that conda-forge/crossenv-feedstock#13 fixed this issue.
